import { rawBaseUrl, resolveRef, resolveRepo } from "./_lib/repo.mjs";

const MODEL_RE = /^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/;
const DEFAULT_MODEL = "google/gemma-4-E4B-it";
const SCRIPT_REPO_PATH = "engines/vlb/vlb_amt_streaming_battery.py";
const QUANT = "Q8_G64";

class ApiError extends Error {
  constructor(message, status = 400) {
    super(message);
    this.name = "ApiError";
    this.status = status;
  }
}

function normalizeModel(value) {
  const raw = String(value || DEFAULT_MODEL).trim().replace(/^\/+|\/+$/g, "");
  if (MODEL_RE.test(raw)) return raw;
  try {
    const url = new URL(raw);
    if (!["huggingface.co", "www.huggingface.co", "hf.co"].includes(url.hostname.toLowerCase())) {
      throw new Error();
    }
    const parts = url.pathname.split("/").filter(Boolean);
    const id = `${parts[0] || ""}/${parts[1] || ""}`;
    if (MODEL_RE.test(id)) return id;
  } catch {
    // handled below
  }
  throw new ApiError("Modelo inválido; use org/modelo do Hugging Face");
}

function buildLauncher({ model, origin, repo = resolveRepo(), ref = resolveRef() }) {
  const raw = rawBaseUrl(repo, ref);
  const scriptUrl = `${raw}/${SCRIPT_REPO_PATH}`;
  return `#!/usr/bin/env python3
# VLB/AMT streaming launcher — generated by ${origin}
# Source weights are fetched tensor-by-tensor with HTTP Range; the full
# upstream checkpoint is never materialized in Colab storage.
import os
import subprocess
import sys
from pathlib import Path
from urllib.request import Request, urlopen

MODEL_ID = ${JSON.stringify(model)}
QUANT = ${JSON.stringify(QUANT)}
SCRIPT_URL = ${JSON.stringify(scriptUrl)}
ROOT = Path("/content/vlb_launcher") if os.path.isdir("/content") else Path.cwd() / "vlb_launcher"
ROOT.mkdir(parents=True, exist_ok=True)
SCRIPT = ROOT / "vlb_amt_streaming_battery.py"

def import_colab_secrets():
    try:
        from google.colab import userdata
    except Exception:
        return
    for name in ("HF_TOKEN", "HUGGING_FACE_HUB_TOKEN", "RIFT_INGEST_TOKEN"):
        if os.environ.get(name):
            continue
        try:
            value = userdata.get(name)
        except Exception:
            value = None
        if value:
            os.environ[name] = str(value)
    if os.environ.get("HF_TOKEN") and not os.environ.get("HUGGING_FACE_HUB_TOKEN"):
        os.environ["HUGGING_FACE_HUB_TOKEN"] = os.environ["HF_TOKEN"]

import_colab_secrets()
os.environ.setdefault("RIFT_RESULTS_ENDPOINT", ${JSON.stringify(`${origin}/api/results`)})
os.environ.setdefault("RIFT_GITHUB_REPOSITORY", ${JSON.stringify(repo)})
os.environ.setdefault("RIFT_SOURCE_REF", ${JSON.stringify(ref)})
print("[VLB] model:", MODEL_ID)
print("[VLB] quant:", QUANT)
print("[VLB] streaming source: ON — no full checkpoint file on disk")
request = Request(SCRIPT_URL, headers={"User-Agent": "rift-vlb-launcher/0.1"})
SCRIPT.write_bytes(urlopen(request, timeout=60).read())
rc = subprocess.call([sys.executable, str(SCRIPT), "--model", MODEL_ID, "--quant", QUANT, "--publish", "on"], env=os.environ.copy())
raise SystemExit(rc)
`;
}

export default {
  async fetch(request) {
    if (!["GET", "HEAD"].includes(request.method)) {
      return new Response("Método não permitido", {
        status: 405,
        headers: { Allow: "GET, HEAD", "Content-Type": "text/plain; charset=utf-8" },
      });
    }
    try {
      const params = new URL(request.url).searchParams;
      const model = normalizeModel(params.get("model"));
      const body = buildLauncher({ model, origin: new URL(request.url).origin });
      return new Response(request.method === "HEAD" ? null : body, {
        status: 200,
        headers: {
          "Cache-Control": "public, max-age=0, s-maxage=300",
          "Content-Type": "text/plain; charset=utf-8",
          "Content-Disposition": 'inline; filename="vlb_launcher.py"',
          "X-Content-Type-Options": "nosniff",
        },
      });
    } catch (error) {
      const status = error instanceof ApiError ? error.status : 500;
      const message = error instanceof ApiError ? error.message : "Erro interno";
      return Response.json({ ok: false, error: message }, { status, headers: { "Cache-Control": "no-store" } });
    }
  },
};

export const _test = { normalizeModel, buildLauncher, DEFAULT_MODEL, QUANT };
