import { rawBaseUrl, resolveRef, resolveRepo } from "./_lib/repo.mjs";

const MODEL_RE = /^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/;
const DEFAULT_MODEL = "google/gemma-4-E4B-it";
const QUANT = "Q8_G64";
const GEMMA_RUNTIME_PACKAGES = [
  "transformers>=5.5.0,<6",
  "accelerate>=1.2,<2",
  "huggingface_hub>=0.30,<2",
  "safetensors>=0.5,<1",
  "requests>=2.32,<3",
];

const VLB_FILES = [
  ["engines/vlb/vlb_amt_streaming_battery.py", "vlb_amt_streaming_battery.py"],
  ["engines/vlb/vlb_runtime.py", "vlb_runtime.py"],
  ["engines/vlb/vlb1_pack.py", "vlb1_pack.py"],
  ["engines/vlb/native_kernel_real_proof.py", "native_kernel_real_proof.py"],
  ["engines/vlb/native/CMakeLists.txt", "native/CMakeLists.txt"],
  ["engines/vlb/native/include/vlb_kernel.h", "native/include/vlb_kernel.h"],
  ["engines/vlb/native/src/vlb_kernel.cpp", "native/src/vlb_kernel.cpp"],
  ["engines/vlb/native/src/vlb_kernel_proof.cpp", "native/src/vlb_kernel_proof.cpp"],
  ["engines/vlb/native/src/vlb_server.cpp", "native/src/vlb_server.cpp"],
];

class ApiError extends Error {
  constructor(message, status = 400) {
    super(message);
    this.name = "ApiError";
    this.status = status;
  }
}

function normalizeModel(value) {
  const raw = String(value || DEFAULT_MODEL).trim().replace(/^\/+|\/+$/g, "");
  if (MODEL_RE.test(raw)) return raw;
  try {
    const url = new URL(raw);
    if (!["huggingface.co", "www.huggingface.co", "hf.co"].includes(url.hostname.toLowerCase())) throw new Error();
    const parts = url.pathname.split("/").filter(Boolean);
    const id = `${parts[0] || ""}/${parts[1] || ""}`;
    if (MODEL_RE.test(id)) return id;
  } catch {
    // handled below
  }
  throw new ApiError("Modelo inválido; use org/modelo do Hugging Face");
}

function buildLauncher({ model, origin, repo = resolveRepo(), ref = resolveRef() }) {
  const raw = rawBaseUrl(repo, ref);
  const files = VLB_FILES.map(([source, destination]) => [`${raw}/${source}`, destination]);
  return `#!/usr/bin/env python3
# VLB native proof launcher v3 — generated by ${origin}
# Source weights are fetched tensor-by-tensor with strict HTTP 206 Range.
# The launcher also builds the VLB-owned C++ kernel and native HTTP server.
import importlib.metadata
import os
import subprocess
import sys
from pathlib import Path
from urllib.request import Request, urlopen

MODEL_ID = ${JSON.stringify(model)}
QUANT = ${JSON.stringify(QUANT)}
FILES = ${JSON.stringify(files)}
PACKAGES = ${JSON.stringify(GEMMA_RUNTIME_PACKAGES)}
ROOT = Path("/content/vlb_launcher") if os.path.isdir("/content") else Path.cwd() / "vlb_launcher"
ROOT.mkdir(parents=True, exist_ok=True)

def import_colab_secrets():
    try:
        from google.colab import userdata
    except Exception:
        return
    for name in ("HF_TOKEN", "HUGGING_FACE_HUB_TOKEN", "RIFT_INGEST_TOKEN"):
        if os.environ.get(name):
            continue
        try:
            value = userdata.get(name)
        except Exception:
            value = None
        if value:
            os.environ[name] = str(value)
    if os.environ.get("HF_TOKEN") and not os.environ.get("HUGGING_FACE_HUB_TOKEN"):
        os.environ["HUGGING_FACE_HUB_TOKEN"] = os.environ["HF_TOKEN"]

def install_conversion_reference_deps():
    current = None
    try:
        current = importlib.metadata.version("transformers")
    except Exception:
        pass
    print("[VLB] transformers before:", current)
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "-U", *PACKAGES])
    print("[VLB] transformers after:", importlib.metadata.version("transformers"))

def download(url, relative):
    destination = ROOT / relative
    destination.parent.mkdir(parents=True, exist_ok=True)
    request = Request(url, headers={"User-Agent": "rift-vlb-native-launcher/0.4"})
    destination.write_bytes(urlopen(request, timeout=60).read())
    print("[VLB] downloaded", relative)

import_colab_secrets()
os.environ.setdefault("RIFT_RESULTS_ENDPOINT", ${JSON.stringify(`${origin}/api/vlb-results`)})
os.environ.setdefault("RIFT_GITHUB_REPOSITORY", ${JSON.stringify(repo)})
os.environ.setdefault("RIFT_SOURCE_REF", ${JSON.stringify(ref)})
print("[VLB] model:", MODEL_ID)
print("[VLB] quant:", QUANT)
print("[VLB] source streaming: STRICT HTTP 206")
print("[VLB] final runtime policy: VLB native only; no llama/bitnet/freetoken fallback")
install_conversion_reference_deps()
for url, relative in FILES:
    download(url, relative)

script = ROOT / "vlb_amt_streaming_battery.py"
rc = subprocess.call(
    [sys.executable, str(script), "--model", MODEL_ID, "--quant", QUANT, "--publish", "on"],
    cwd=str(ROOT),
    env=os.environ.copy(),
)
raise SystemExit(rc)
`;
}

export default {
  async fetch(request) {
    if (!["GET", "HEAD"].includes(request.method)) {
      return new Response("Método não permitido", {
        status: 405,
        headers: { Allow: "GET, HEAD", "Content-Type": "text/plain; charset=utf-8" },
      });
    }
    try {
      const params = new URL(request.url).searchParams;
      const model = normalizeModel(params.get("model"));
      const body = buildLauncher({ model, origin: new URL(request.url).origin });
      return new Response(request.method === "HEAD" ? null : body, {
        status: 200,
        headers: {
          "Cache-Control": "public, max-age=0, s-maxage=300",
          "Content-Type": "text/plain; charset=utf-8",
          "Content-Disposition": 'inline; filename="vlb_launcher.py"',
          "X-Content-Type-Options": "nosniff",
        },
      });
    } catch (error) {
      const status = error instanceof ApiError ? error.status : 500;
      const message = error instanceof ApiError ? error.message : "Erro interno";
      return Response.json({ ok: false, error: message }, { status, headers: { "Cache-Control": "no-store" } });
    }
  },
};

export const _test = {
  normalizeModel,
  buildLauncher,
  DEFAULT_MODEL,
  QUANT,
  VLB_FILES,
  GEMMA_RUNTIME_PACKAGES,
};
